/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CasesRasskazovkaRouteImport } from './routes/cases.rasskazovka'
import { Route as CasesMakovkaRouteImport } from './routes/cases.makovka'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesRasskazovkaRoute = CasesRasskazovkaRouteImport.update({
  id: '/cases/rasskazovka',
  path: '/cases/rasskazovka',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesMakovkaRoute = CasesMakovkaRouteImport.update({
  id: '/cases/makovka',
  path: '/cases/makovka',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cases/makovka': typeof CasesMakovkaRoute
  '/cases/rasskazovka': typeof CasesRasskazovkaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cases/makovka': typeof CasesMakovkaRoute
  '/cases/rasskazovka': typeof CasesRasskazovkaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cases/makovka': typeof CasesMakovkaRoute
  '/cases/rasskazovka': typeof CasesRasskazovkaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cases/makovka' | '/cases/rasskazovka'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cases/makovka' | '/cases/rasskazovka'
  id: '__root__' | '/' | '/cases/makovka' | '/cases/rasskazovka'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CasesMakovkaRoute: typeof CasesMakovkaRoute
  CasesRasskazovkaRoute: typeof CasesRasskazovkaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/rasskazovka': {
      id: '/cases/rasskazovka'
      path: '/cases/rasskazovka'
      fullPath: '/cases/rasskazovka'
      preLoaderRoute: typeof CasesRasskazovkaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/makovka': {
      id: '/cases/makovka'
      path: '/cases/makovka'
      fullPath: '/cases/makovka'
      preLoaderRoute: typeof CasesMakovkaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CasesMakovkaRoute: CasesMakovkaRoute,
  CasesRasskazovkaRoute: CasesRasskazovkaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
